/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119856-gbe46370941-20250608"
#endif /* AVUTIL_FFVERSION_H */
